[package]
name = "paradox-server"
version = "0.1.0"
authors = ["Xiphoseer <xiphoseer@mailbox.org>"]
edition = "2018"

[dependencies]
handlebars = "3.5"
pretty_env_logger = "0.4.0"
structopt = "0.3.21"
color-eyre = "0.5.10"
mapr = "0.8.0"
paradox-typed-db = { path = "../paradox-typed-db" }
percent-encoding = "2.1.0"
regex = "1.4"
toml = "0.5"

[dependencies.warp]
version = "0.3"
features = ["tls"]

[dependencies.assembly-core]
version = "0.2.1"

[dependencies.assembly-data]
version = "0.3.0"
default-features = false
features = ["serde-derives"]

# Holds data in insertion order
[dependencies.linked-hash-map]
version = "0.5.3"
features = ["serde_impl"]

[dependencies.tokio]
version = "1"
features = ["rt-multi-thread", "macros", "signal"]

[dependencies.serde]
version = "1"
features = ["derive"]
