[package]
name = "paradox-server"
version = "0.1.0"
authors = ["Xiphoseer <xiphoseer@mailbox.org>"]
edition = "2018"

[dependencies]
pretty_env_logger = "0.4.0"
structopt = "0.3.21"
color-eyre = "0.5.10"
mapr = "0.8.0"
toml = "0.5"

[dependencies.warp]
version = "0.2.5"
features = ["tls"]

[dependencies.assembly-data]
version = "0.3.0-beta.0"
path = "../assembly/modules/data"

[dependencies.linked-hash-map]
version = "0.5.3"
features = ["serde_impl"]

[dependencies.tokio]
version = "0.2"
features = ["macros", "signal"]

[dependencies.serde]
version = "1"
features = ["derive"]
