[general]
port = 3030
public = false
domain = "localhost"

[data]
cdclient = "../cdclient.fdb"
explorer_spa = "../../explorer/docs"
lu_res_cache = "../../../repos/lu-res"
lu_json_cache = "../../../repos/lu-json"
locale = "../../../install/ulcdr/locale/locale.xml"
