on:
  push:
    branches: [main]

name: Release Build

jobs:
  linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run cargo build
        run: cargo build --release
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: paradox-server-linux
          path: target/release/paradox-server
  windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run cargo build
        run: cargo build --release
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: paradox-server-windows
          path: target/release/paradox-server.exe
